// ||... ar lang ...||
Map<String, String> ar = {
  'LoginInToYourAccount': 'تسجيل الدخول الى حسابك',
  'Email': 'البريد الالكتروني',
  'Password': 'كلمة المرور',
  'SignIn': 'تسجيل الدخول',
  'ForgotPassword': 'هل نسيت كلمة المرور؟',
  "Don'tHaveAnAccount": "ليس لدك حساب؟",
  'SignUp': 'انشاء حساب',
  'ThisFieldIsRequired': 'هذا الحقل مطلوب',
  'ThisIsNotEmailFormat': 'هذا ليس صيغة بريد الكتروني',
  'EnterPassword': 'أدخل كلمة المرور',
  'EnterEmail': 'أدخل البريد الالكتروني',
  'Skip': 'تخطي',
  'CreateNewAccount': 'انشاء حساب جديد',
  'FullName': 'الاسم الكامل',
  'EnterFullName': 'ادخل اسمك الكامل',
  'MobileNumber': 'رقم الهاتف',
  'EnterMobileNumber': 'ادخل رقم الهاتف',
  'City': 'المدينة',
  'ChooseACity': 'اختر المدينة',
  'ConfirmPassword': 'تاكيد كلمة المرور',
  'EnterConfirmPassword': 'اكد كلمة المرور',
  'ResetPassword': 'استعادة كلمة المرور',
  'Send': 'ارسال',
  'Home': 'الرئيسية',
  'Products': 'منتجات',
  'Offer': 'عرض',
  'AddToCart': 'اضافة الى السلة',
  'Notifications': 'الاشعارات',
  'NoNotifications': 'لا يوجد اشعارات',
  'NoSearchResults': 'لا يوجد نتائج',
  'Orders': 'الطلبات',
  'Status': 'الحالة',
  'OrderId': 'رقم الطلب',
  'Total': 'المجموع',
  'Favorites': 'المفضلة',
  'FavoritesIsEmpty': 'المفضلة فارغة',
  'NoProducts': 'لا يوجد منتجات',
  'Offers': 'العروض',
  'NoOffersAvailable': 'لا يوجد عروض متاحة',
  'AboutUs': 'من نحن',
  'Q&F': 'الأسئلة الشائعة',
  'Settings': 'الاعدادات',
  'ChangeLanguage': 'تغيير اللغة',
  'ChangePassword': 'تغيير كلمة المرور',
  'EnterOldPassword': 'ادخل كلمة المرور القديمة',
  'ShareApp': 'مشاركة التطبيق',
  'TermsOfUse': 'شروط الاستخدام',
  'PrivacyPolicy': 'سياسة الخصوصية',
  'ContactUs': 'تواصل معنا',
  'ContactForm': 'صندوق التواصل',
  'Message': 'الرسالة',
  'ContactInfo': 'معلومات التواصل',
  'TapBackAgainToLeave': 'اضغط مرة اخرى للخروج',
  'SignOut': 'تسجيل الخروج',
  'Reviews': 'التعليقات',
  'Details': 'التفاصيل',
  'AverageRating': 'معدل التقييم',
  'WhatPeopleAreSaying': 'ماذا قال الزبائن :',
  'RelatedProducts': 'منتجات ذات صلة',
  'Quantity': 'الكمية',
  'Size': 'الحجم',
  'Views': 'مشاهدات',
  'Likes': 'اعجابات',
  'SAR': 'ريال',
  'Payment': 'الدفع',
  'Continue': 'استمرار',
  'SearchAboutProduct': 'ابحث عن منتج..',
  'Loading': 'الرجاء الانتظار...',
  'EnterMessage': 'ادخل الرسالة',
  'EditProfile': 'تعديل الملف الشخصي',
  'Profile': 'حسابي',
  'PersonalInformation': 'المعلومات الشخصية',
  'Save': 'حفظ',
  'Failed': 'عذراً',
  'Success': 'نجاح',
  'ChooseFrom': 'اختر من',
  'Gallery': 'المعرض',
  'Camera': 'الكاميرا',
  'SelectACity': 'اختر مدينة',
  'NoImagesAvailable': 'لا يوجد صور متاحة',
  'Coffee': 'كوفي',
  'Salon': 'الصالون',
  'SeeAll': 'عرض الكل',
  'All': 'الكل',
  'Cart': 'السلة',
  'CheckOut': 'الدفع',
  'Discount': 'الخصم',
  'Additions': 'الاضافات',
  'CustomerName': 'اسم المستهلك',
  'DeliveryMethod': 'طريقة استلام الطلب',
  'DeliveryAddress': 'عنوان التوصيل',
  'DeliveryTime': 'وقت التوصيل',
  'Delivery': 'توصيل',
  'Takeout': 'مع الخروج',
  'TableNumber': 'رقم الطاولة',
  'PaymentMethod': 'طريقة الدفع',
  'PayOnDelivery': 'الدفع عن الاستلام',
  'AddItemsToGetStarted': 'اضف منتجات للبدأ',
  'CartIsEmpty': 'السلة فارغة !',
  'SubTotal': 'المجموع الفرعي',
  'Favorite': 'المفضلة',
  'PayOnline': 'دفع الكتروني',
  'DiscountCode': 'كود الخصم',
  'Check': 'فحص',
  'SomethingWentWrong': 'حدث خطأ ما',
  'Services': 'الخدمات',
  'BookingDetails': 'تفاصيل الحجز',
  'DeliveryCost': 'تكلفة التوصيل',
  'ChooseASection': 'اختر القسم',
  'OrderNow': 'اطلب الأن',
  'BookNow': 'احجز الان',
  'BookingDate': 'تاريخ الحجز',
  'BookingTime': 'وقت الحجز',
  'More': 'المزيد',
  'Store': 'المتجر',
  'Booked': 'تم الحجز',
  'Date': 'التاريخ',
  'OrderDetails': 'تفاصيل الطلب',
  'Time': 'الوقت',
  'Cash': 'نقداً',
  'NoDetails': 'لا يوجد تفاصيل',
  'Online': 'الكتروني',
  'Comment': 'التعليق',
  'RateProduct': 'قيم المنتج',
  'TotalAdditions': 'مجموع الاضافات',
  'New': 'جديد',
  'Preparing': 'قيد التحضير',
  'OnDelivery': 'جاري التوصيل',
  'Delivered': 'تم التوصيل',
  'Ready': 'جاهز للتوصيل',
  'TryAgain': 'محاولة مرة اخرى',
  'NoOrders': 'لا يوجد طلبات !',
  'NoReviews': 'لا يوجد تعليقات',
  'NoServices': 'لا يوجد خدمات',
  'YouHaveDiscount': 'لديك خصم بنسبة',
  'DiscountCodeIsInvalid': 'كود الخصم غير صحيح',
  'YouMustSelectALocation !': 'يجب عليك اختيار الموقع',
  'ProfileIsAlreadyUpdated': 'حسابك محدث بالفعل',
  'PleaseDetermineAQuantity': 'الرجاء تحديد الكمية المطلوبة !',
  'YouMustSpecifyTheProductSize': 'يجب عليك اختيار حجم المنتج اولا !',
  'ConfirmPasswordDoesNotMatchPassword':
      'تاكيد كلمة المرور لا تتطابق مع كلمة المرور',
  "vat" : "الضريبة",
};
