// ||... en lang ...||
Map<String, String> en = {
  'LoginInToYourAccount': 'Login in to your account',
  'Email': 'Email',
  'Password': 'Password',
  'SignIn': 'Sign in',
  'ForgotPassword': 'Forgot Password?',
  "Don'tHaveAnAccount": "Don't have an account",
  'SignUp': 'Sign up',
  'ThisFieldIsRequired': 'This field is required',
  'EnterPassword': 'Enter password',
  'EnterEmail': 'Enter email address',
  'ThisIsNotEmailFormat': 'This is not email format',
  'Skip': 'Skip',
  'CreateNewAccount': 'Create New Account',
  'FullName': 'Full Name',
  'EnterFullName': 'Enter full name',
  'MobileNumber': 'Mobile Number',
  'EnterMobileNumber': 'Enter mobile number',
  'City': 'City',
  'ChooseACity': 'Choose a city',
  'ConfirmPassword': 'Confirm Password',
  'EnterConfirmPassword': 'Enter confirm password',
  'ResetPassword': 'Reset Password',
  'Send': 'Send',
  'Home': 'Home',
  'Products': 'Products',
  'Offer': 'Offer',
  'AddToCart': 'Add To Cart',
  'Notifications': 'Notifications',
  'NoNotifications': 'No Notifications',
  'Orders': 'Orders',
  'Status': 'Status',
  'OrderId': 'OrderId',
  'Total': 'Total',
  'Favorites': 'Favorites',
  'FavoritesIsEmpty': 'Favorites Is Empty',
  'NoProducts': 'No Products',
  'NoOrders': 'No Orders Found !',
  'Offers': 'Offers',
  'NoOffersAvailable': 'No Offers Available',
  'AboutUs': 'About us',
  'Q&F': 'Q&F',
  'Settings': 'Settings',
  'ChangeLanguage': 'Change Language',
  'ChangePassword': 'Change Password',
  'EnterOldPassword': 'Enter old password',
  'ShareApp': 'Share App',
  'TermsOfUse': 'Terms Of Use',
  'PrivacyPolicy': 'Privacy Policy',
  'ContactUs': 'Contact Us',
  'ContactForm': 'Contact Form',
  'ContactInfo': 'Contact Info',
  'Message': 'Message',
  'TapBackAgainToLeave': 'Tap back again to leave',
  'SignOut': 'SignOut',
  'Reviews': 'Reviews',
  'Details': 'Details',
  'AverageRating': 'Average Rating',
  'WhatPeopleAreSaying': 'What people are saying',
  'RelatedProducts': 'Related Products',
  'Quantity': 'Quantity',
  'Size': 'Size',
  'Views': 'Views',
  'Likes': 'Likes',
  'SAR': 'SAR',
  'SearchAboutProduct': 'Search about product...',
  'NoSearchResults': 'No Search Results',
  'Loading': 'Loading...',
  'EnterMessage': 'Enter Message',
  'EditProfile': 'Edit Profile',
  'Profile': 'Profile',
  'PersonalInformation': 'Personal Information',
  'Save': 'Save',
  'Failed': 'Failed',
  'Success': 'Success',
  'ChooseFrom': 'Choose From',
  'Gallery': 'Gallery',
  'Camera': 'Camera',
  'SelectACity': 'Select a city',
  'NoImagesAvailable': 'No images available',
  'Coffee': 'Coffee',
  'Salon': 'Salon',
  'SeeAll': 'See all',
  'All': 'All',
  'Cart': 'Cart',
  'CartIsEmpty': 'Cart Is Empty !',
  'SubTotal': 'Sub Total',
  'CheckOut': 'Check Out',
  'Discount': 'Discount',
  'Additions': 'Additions',
  'CustomerName': 'Customer Name',
  'DeliveryAddress': 'Delivery Address',
  'DeliveryMethod': 'Delivery Method',
  'DeliveryTime': 'Delivery Time',
  'TableNumber': 'Table Number',
  'PaymentMethod': 'Payment method',
  'Payment': 'Payment',
  'Continue': 'Continue',
  'PayOnDelivery': 'Pay On  Delivery',
  'PayOnline': 'Pay Online',
  'Check': 'Check',
  'Cash': 'Cash',
  'NoDetails': 'No Details',
  'Online': 'Online',
  'New': 'New',
  'Preparing': 'Preparing',
  'OnDelivery': 'OnDelivery',
  'Delivery': 'Delivery',
  'Takeout': 'Takeout',
  'Delivered': 'Delivered',
  'Ready': 'Ready',
  'TotalAdditions': 'total additions',
  'DeliveryCost': 'Delivery cost',
  'OrderNow': 'Order Now',
  'AddItemsToGetStarted': 'Add items to get started',
  'Favorite': 'Favorite',
  'SomethingWentWrong': 'something went wrong',
  'Services': 'Services',
  'ChooseASection': 'Choose a section',
  'BookNow': 'Book Now',
  'BookingDate': 'Booking Date',
  'BookingTime': 'Booking Time',
  'More': 'More',
  'Store': 'Store',
  'Date': 'Date',
  'Time': 'Time',
  'Booked': 'Booked',
  'Comment': 'Comment',
  'RateProduct': 'Rate Product',
  'BookingDetails': 'Booking Details',
  'OrderDetails': 'Order Details',
  'TryAgain': 'Try Again',
  'NoServices': 'No Services Found',
  'NoReviews': 'No Reviews Found',
  'YouHaveDiscount': 'You Have Discount',
  'YouMustSelectALocation !': 'You must select a location !',
  'DiscountCodeIsInvalid': 'Discount code is invalid',
  'ProfileIsAlreadyUpdated': 'Profile Is Already Updated',
  'PleaseDetermineAQuantity': 'Please determine a quantity !',
  'YouMustSpecifyTheProductSize': 'You must specify the product size first ! ',
  'ConfirmPasswordDoesNotMatchPassword':
      'Confirm password does not match password',
  "vat": "vat",
};
